import type { Content } from "./fr";

const en: Content = {
  meta: {
    title: "Mohamed Diomande · Full-Stack Developer & Project Manager",
    description:
      "I build web and mobile apps that users actually adopt. Full-Stack Developer and Project Manager based in Grand-Bassam, Côte d'Ivoire.",
  },
  nav: {
    about: "About",
    skills: "Skills",
    projects: "Projects",
    services: "Services",
    contact: "Contact",
    cta: "Let's talk",
    language: "Language",
  },
  hero: {
    aboutTab: ["About", "me"],
    worksTitle: "Works",
    welcome: {
      title: "Let's build the product that accelerates your growth.",
      highlight: "accelerates your growth.",
      ctaPrimary: "Start a project",
      ctaSecondary: "See my work",
      text: "Business platforms, mobile apps and AI automation: I run your project from A to Z, as your single point of contact.",
    },
    categories: [
      { label: "E-health", count: 2 },
      { label: "Education & e-learning", count: 2 },
      { label: "E-commerce & logistics", count: 1 },
      { label: "Mobile apps", count: 3 },
      { label: "Institutional websites", count: 2 },
      { label: "SaaS", count: 2 },
      { label: "AI agents", count: 1 },
    ],
    firstName: "Mohamed",
    lastName: "Diomande",
    greeting: "I'm",
    title: "Software Engineer",
    role: "Full-Stack Developer & Project Manager",
    more: "More contacts",
  },
  intro: {
    words: ["Discipline.", "Rigor.", "Precision.", "Reliability.", "Commitment."],
    label: "How I work",
    principles: [
      { title: "Solid from the first line", text: "Architecture built to last: structured APIs, protected data, controlled releases. Your product holds up as your business grows.", tag: "Architecture & security" },
      { title: "Web and mobile, built for your users", text: "Fast web interfaces with React and Next.js, React Native mobile apps that work even on unstable connections.", tag: "Front-end web & mobile" },
      { title: "Accelerated by AI", text: "AI agents speed up coding, testing and review, under my control. And I build them into your products to automate your tasks.", tag: "AI agents" },
      { title: "Managed end to end", text: "Scoping with your team, regular demos, production release and user training. One point of contact, from start to finish.", tag: "Project management" },
    ],
    stats: {
      live: { value: "7", label: "platforms and websites in production" },
      itil: { value: "ITIL® 4", label: "Foundation certified" },
    },
  },
  about: {
    eyebrow: "About · My method",
    steps: [
      { word: "Scope", text: "Understand the business before coding." },
      { word: "Design", text: "Clear interfaces, built around users." },
      { word: "Ship", text: "Fast, with AI agents. Under human control." },
      { word: "Train", text: "Support teams until real adoption." },
      { word: "Follow up", text: "Regular demos, clear tracking, field feedback." },
    ],
  },
  skills: {
    eyebrow: "Skills",
    title: "My skills.",
    highlight: "skills",
    stack: [
      { name: "React", icon: "react", family: "Front-end" },
      { name: "Next.js", icon: "next", family: "Front-end" },
      { name: "Vite", icon: "vite", family: "Front-end" },
      { name: "Python", icon: "python", family: "Back-end" },
      { name: "Django", icon: "django", family: "Back-end" },
      { name: "Node.js", icon: "node", family: "Back-end" },
      // { name: "React Native", icon: "react", family: "Mobile" },
      { name: "WatermelonDB", icon: "watermelon", family: "Mobile" },
      { name: "PostgreSQL", icon: "postgres", family: "Data" },
      { name: "MySQL", icon: "mysql", family: "Data" },
      { name: "SQL Server", icon: "sqlserver", family: "Data" },
      { name: "Docker", icon: "docker", family: "Infra" },
      { name: "MinIO", icon: "minio", family: "Infra" },
      { name: "Git", icon: "git", family: "Tools" },
      { name: "Claude Code", icon: "claude", family: "AI agents" },
      { name: "Codex", icon: "codex", family: "AI agents" },
      { name: "Kilo Code", icon: "kilo", family: "AI agents" },
    ],
  },
  projects: {
    eyebrow: "Selected projects",
    title: ["Ideas turned into", "products", "that run."],
    text: "From healthcare to e-commerce, platforms designed, built and shipped to production for real users.",
    cta: "Start a project",
    privateLabel: "Private · demo on request",
    visit: "Visit site",
    next: "Next project",
    items: [
      { id: "learn", name: "Learn Cybersécurité en Afrique", short: "Learn", domain: "E-learning", role: "Full-stack developer", url: "https://learn.cybersecuriteenafrique.com", image: "/images/project-learn.webp", preview: "learn", metric: { value: "Live", label: "in production" }, line: "Certification courses and mock exams in real exam conditions.", stack: [] },
      { id: "gesci", name: "GESCI Agency", short: "GESCI", domain: "Institutional website", role: "Design · Development · Launch", url: "https://gesci.ci", image: "/images/project-gesci.webp", preview: "web", metric: { value: "2025", label: "live since" }, line: "Architecture, interfaces and production release of the agency's website.", stack: [] },
      { id: "commission", name: "Competition Commission", short: "Commission", domain: "Institutional website", role: "Design · Development · Launch", url: "https://commissiondelaconcurrence.gouv.ci", image: "/images/project-commission.webp", preview: "web", metric: { value: "2023", label: "live since" }, line: "The official website of Côte d'Ivoire's competition regulator.", stack: [] },
      { id: "tuyo", name: "Tuyo AI", short: "Tuyo AI", domain: "AI agent", role: "Personal project", image: "/images/project-tuyo.webp", preview: "ai", metric: { value: "AI", label: "analyzes every evening" }, line: "An AI agent analyzes matches and suggests the best accumulators.", stack: [] },
    ],
  },
  services: {
    eyebrow: "Services",
    title: "What I build for you.",
    highlight: "build",
    items: [
      { title: "Web & mobile apps", icon: "layout" },
      { title: "SaaS", icon: "cloud" },
      { title: "UI/UX design", icon: "pen" },
      { title: "AI agents", icon: "bot" },
      { title: "Project management", icon: "route" },
    ],
    stat: { value: "7+", label: "platforms in production" },
  },
  education: {
    eyebrow: "Education & certification",
    title: "Solid foundations, continuous standards.",
    cert: { name: "ITIL® 4 Foundation", issuer: "PeopleCert", date: "July 2026" },
    items: [
      // { degree: "PhD (admitted)", school: "INPHB, Félix Houphouët-Boigny National Polytechnic Institute", period: "2026 → 2030", detail: "Frugal artificial intelligence for medical diagnosis" },
      { degree: "Master's in Computer Systems & Software Engineering", school: "ESATIC", period: "2021 → 2023", detail: "" },
      { degree: "Bachelor's in Web Technologies & Digital Imaging", school: "ESATIC", period: "2018 → 2021", detail: "" },
    ],
  },
  contact: {
    eyebrow: "Contact",
    title: "Have a web or mobile app project? Let's talk.",
    highlight: "Let's talk.",
    text: "Tell me what you want to build, who it's for and your timeline. I'll come back with a clear plan for a polished product, delivered fast.",
    email: "dioomande.mohamed@gmail.com",
    phone: "+225 07 48 15 46 94",
    whatsapp: "2250748154694",
    linkedin: "https://www.linkedin.com/in/mohamed-diomande-4190111a4/",
    location: "Grand-Bassam, Côte d'Ivoire · available for remote work",
    form: {
      name: "Your name",
      email: "Your email",
      project: "Your project: what, for whom, what timeline?",
      send: "Send message",
      subject: "Project via portfolio",
      sending: "Sending…",
      success: "Thank you! Your message is on its way, I'll get back to you soon.",
      error: "Sending failed. Try again or email me directly:",
      invalid: "Please check your name, email and message.",
    },
    labels: { email: "Email", phone: "Phone / WhatsApp", location: "Location" },
    confirmation: {
      subject: "I've received your message",
      title: "Thank you, your project is in good hands.",
      greeting: "Hi {name},",
      body: "Your message has arrived. I'm reviewing it and will get back to you very soon, usually within 24 to 48 hours, with a first answer about your project.",
      cta: "See my work",
      footer: "diomoh · Web apps, mobile apps and AI agents",
      signature: "Full-Stack Developer & Project Manager",
      note: "This email was sent automatically after your message on diomoh.com.",
    },
  },
  guide: {
    hero: "Start here",
    principles: "How I work",
    method: "My method",
    skills: "My tools",
    projects: "My work",
    services: "What I do",
    education: "My background",
    contact: "Write to me",
  },
  footer: { rights: "All rights reserved.", top: "Back to top" },
};

export default en;
